apiVersion: v1
kind: Service
metadata:
  name: strapi
  namespace: strapi
spec:
  selector:
    app: strapi
    tenant: strapi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 1337
  type: LoadBalancer
