apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: default
  creationTimestamp: null
  labels:
    io.kompose.service: mysql-runtime
  name: mysql-runtime
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
