---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    # Replace the email address with your own contact email
    email: bot@sredevops.cl
    # The server is replaced in /clusters/production/infrastructure.yaml
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-nginx
    solvers:
      - http01:
          ingress:
            class: nginx
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: cloudflare-api
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: ngeorger@gmail.com

    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: cloudflare-api-issuer-account-key
    # ACME DNS-01 provider configurations
    solvers:
    # An empty 'selector' means that this solver matches all domains
      - selector:
          dnsNames:
          - sredevops.cl
        dns01:
          cloudflare:
            email: ngeorger@gmail.com
            # !! Remember to create a k8s secret before
            # kubectl create secret generic cloudflare-api-key-secret
            apiKeySecretRef:
              name: cloudflare-api-key-secret
              key: api-key
---
