apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: external-dns-helm-chart-value-overrides
  namespace: external-dns
data:
  values.yaml: |-
    cloudflare:
      secretName: "cloudflare-api-token"
      proxied: true
